esphome:
  name: piscina_luzes_1
  platform: ESP32
  board: esp32doit-devkit-v1
  
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.29.37
    gateway: 192.168.29.1
    subnet: 255.255.255.0

api:

logger:

ota:
  safe_mode: true
  password: animal
  
captive_portal:

switch:
  - platform: gpio
    name: "Piscina - Luzes - Gourmet - Churrasqueira"
    id: piscina_luzes_gourmet_churrasqueira
    inverted: true
    pin: GPIO15

  - platform: gpio
    name: "Piscina - Luzes - Gourmet - Lustres da Ilha"
    id: piscina_luzes_gourmet_lustres_ilha
    inverted: true
    pin: GPIO02

  - platform: gpio
    name: "Piscina - Luzes - Gourmet - Jardim da Piscina"
    id: piscina_luzes_jardim_piscina
    inverted: true
    pin: GPIO16

  - platform: gpio
    name: "Piscina - Luzes - Arandelas da Piscina"
    id: piscina_luzes_arandelas_piscina
    inverted: true
    pin: GPIO17

  - platform: gpio
    name: "Piscina - Luzes - Banheiro - Chuveiro"
    id: piscina_luzes_banheiro_chuveiro
    inverted: true
    pin: GPIO05

  - platform: gpio
    name: "Piscina - Luzes - Banheiro - Pia"
    id: piscina_luzes_banheiro_pia
    inverted: true
    pin: GPIO18

  - platform: gpio
    name: "Piscina - Luzes - Cobertura - Arandelas"
    id: piscina_luzes_cobertura_arandelas
    inverted: true
    pin: GPIO19

  - platform: gpio
    name: "Piscina - Luzes - Cascata"
    id: piscina_luzes_cascata
    inverted: true
    pin: GPIO21
